### ISSUE TITLE
[shared] Skip flux installation if installed

### ISSUE THREAD

**Issue by adityajoshi12** [hyperledger/bevel#2438] opened 2023-12-01 18:21 UTC
**Describe the bug**
Currently while running the deployments bevel always tries to install the flux, even in the case when the flux is already installed.

**To Reproduce**
1. Run the deployment twice

**Expected behavior**
If the flux is already installed, the installation should be skipped if there is an instance available in the cluster with namespace `flux-{{ network.env.type }} `

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. MacOS]

**Additional context**

**Comment by suvajit-sarkar** [comment] 2023-12-04 11:03
flux installation is idempotent. Is running the flux command again causing any issue ?

**Comment by suvajit-sarkar** [comment] 2023-12-15 10:38
closing this issue, as this is expected and not a bug

**Closed by suvajit-sarkar** 2023-12-15 10:38 UTC
Labels: bug
