### ISSUE TITLE
CHANNEL JOINED NEW ORG CAN'T  CREATE  NEW CHANNEL- error "member ORGMSP which is not in the consortium"

### ISSUE THREAD

**Issue by aswath-edx** [hyperledger/bevel#2217] opened 2023-04-18 11:23 UTC
i created fabric network with edxorg001 and edxorg002 and channel name master-channel and i join edxorg137 and edxorg2255 in that channel, next i trying to create new channel with edxorg137 and edxorg2255. but when i trying to create new channel  i got error  like ""Attempted to include member edxorg2255MSP which is not in the consortium"""
the new org join first channel successfully
and iam trying to create new channel with latest added new org. then i got this error

![Screenshot from 2023-04-18 11-41-04](https://user-images.githubusercontent.com/121422505/232762032-a5cd75ed-8840-42d6-bd8d-4207a8361c30.png)

**Comment by shubham-edx** [comment] 2023-04-19 05:06
following

**Comment by aswath-edx** [comment] 2023-04-20 03:54
@sownak yes the edxorg137 edxorg137 added in the first channel and the process is completed. the issue is that after join the orgs , the new joined org cant create channel 

[Screenshot from 2023-04-20 09-23-11](https://user-images.githubusercontent.com/121422505/233254084-2f586b96-b269-4e76-8d04-71df90ed2c48.png)

**Comment by aswath-edx** [comment] 2023-04-20 04:46
![Screenshot from 2023-04-20 10-13-38](https://user-images.githubusercontent.com/121422505/233260670-e68cb5f3-4ba2-4ff
![Screenshot from 2023-04-20 10-13-40](https://user-images.githubusercontent.com/121422505/233260675-a8194127-96df-4a37-8563-aa62f4a793a8.png)
4-b7f3-e4d7217373ae.png)
![Screenshot from 2023-04-20 10-13-42](https://user-images.githubusercontent.com/121422505/233260689-3e01fa85-5c7f-4c5e-8cfc-7129ea3f9392.png)
![Screenshot from 2023-04-20 10-13-43](https://user-images.githubusercontent.com/121422505/233260693-fc13bf30-8fd3-42c8-8e1f-4d0891546d08.png)

**Comment by suvajit-sarkar** [comment] 2023-04-24 12:24
Not able to reproduce the issue. Closing it

**Closed** 2023-04-24 12:24 UTC
Labels: bug
